arch: amd64
os: linux
dist: noble
language: minimal
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/jdk"
    - "$HOME/mvn"
branches:
  only:
    - main
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
  # install temurin 25
  - |
    if [ ! -d "$HOME/jdk" ]; then
      mkdir --parents $HOME/jdk
      curl --fail --silent --show-error --location --output "$HOME/jdk.tar.gz" \
        https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.2%2B10/OpenJDK25U-jdk_x64_linux_hotspot_25.0.2_10.tar.gz
      echo "987387933b64b9833846dee373b640440d3e1fd48a04804ec01a6dbf718e8ab8  $HOME/jdk.tar.gz" | sha256sum --check          
      tar --extract --gunzip --strip-components=1 --directory="$HOME/jdk" "$HOME/jdk.tar.gz"
      rm "$HOME/jdk.tar.gz"
    fi
  # install maven 3.9.11
  - |
    if [ ! -d "$HOME/mvn" ]; then
      mkdir --parents "$HOME/mvn"
      curl --fail --silent --show-error --location --output "$HOME/mvn.tar.gz" \
        https://archive.apache.org/dist/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      echo "4b7195b6a4f5c81af4c0212677a32ee8143643401bc6e1e8412e6b06ea82beac  $HOME/mvn.tar.gz" | sha256sum --check
      tar --extract --gunzip --strip-components=1 --directory="$HOME/mvn" "$HOME/mvn.tar.gz"
      rm "$HOME/mvn.tar.gz"
    fi
  # copy maven settings
  - mkdir --parents $HOME/.m2
  - rsync --archive --checksum travis.settings.xml $HOME/.m2/settings.xml
script:
  - echo "JAVA_HOME=$JAVA_HOME"
  - echo "PATH=$PATH"
  - java -version
  - mvn -version
  - mvn clean verify --batch-mode --no-transfer-progress --activate-profiles coverage
deploy:
  - provider: releases
    token:
      secure: IBaApKGv7jH2aidxsthwzz3ZfUdOCOlmOgj3VyArzNmjNqYJMj9oPu7aNcI6ckk2xov8DxZknk1YlwONiN+gMKHrGqMR3Ckz96QDvt2QnyIOFsd8pAfaQqeMQyY/SJkFfWFFlDFmwaamxX08jwPg4JmSjcZ45IB12EiGAGtOU2DY1UH8kCtQJzADMWHPffS6OnzAfKTDPrZuuxZ0ogiav/se3aEvOWf3/sVKeeMIHDv1Hi4DaNrXvd1CG+ivtFoQMGr3F4McZSCo+DpO/XW7/RAjkeeM8xd3qV2ng3SbF9iAfGVG3jLmfwAsNMik5rdoQTgMV665ftx8P//dimv3JQYUhPdBFcWl7pmhE2oldWDhjT/a1dkkCoqK8Rjo7F0swDdJy3ztyKCxeAA9zF/4pc3kL2fzS92w5Iltl2IZpWZUgHuhtIz9WCJ1pws9Y+fjEe+vHdVIIIIZ9jiSg0ei8yua0DW9dj7AUVUZ7Wz2IIF5jYug3qluu5dAnkq8YQB15fMUniCaPODO2WNyZQa5IaTlXp+DRoguqE95VxfpkwFOzibC1ppPciMuqBBYgMML2X1PVV93A7nOYU2UeIvAU18CotTJnY1n7p+Wnj/gdy5lEv158GHscdnZb01EHk4vZd7tAzat7/3qLcA2WkDiVp6Ln4eVYK4VSD2gVmrTPKQ=
    file: target/vip-utils.jar
    on:
      tags: true
  - provider: script
    script: mvn clean deploy --batch-mode --no-transfer-progress
    on:
      tags: true
env:
  global:
    - JAVA_HOME=$HOME/jdk
    - PATH=$JAVA_HOME/bin:$HOME/mvn/bin:$PATH
    - secure: hXgBpskONS0Bwfp//8deUrpZQXlg1Pa+RqrVAOPhx9BPSabjKtFZ74d8f+QAmcwQJd5K8zILDd6upHTjhiyPAz2r4ZmnNOkI1hXNDL33wrZyVFh+bVP0jTQHltZ0I7byqut3OF9YDMlPCSDxxTBaY1asM6mBsROMQCSf17/3/XqadfzBC2KYS2c1sBFaSXyBsD9l1JeVV0Z8NSVTcOPGjTBOJe85T30FTJpZI1Zxlv8omfSTGjDVHRBHKq7SFdWCqC9HCWZDg3AQRq4lxfCc74iI9pNmx96GWq3c3RFHz/cjPPUGn/5nix9RYE7OQiiwToHG+dW8JrqLHvvX5xk5R0zh/C3mIXVZKXw9bISmdsO80QqQfxboCNEUaoFH51HscPqbrRWmtzgHNdQyUUAUpBVpG9yYZTJ0buRyNJFluaGad+itVWksWzNb/oAjNxMBzssuzXnAYFLQ3HdswRYX2fbHBxHhlFlBPtf6EGEK0vIJ8IEeq7eQbhJYQbnzjmA9jfxyNsU3hp/A8LicBmPNWGvvno3NGtWrHGu+VLU2TWqXYjWsE4Pso8fg0UKFbVrlVi+DCx5Okt5DHLNWBkFgObyg0Ec0ffOuJfaH/0i2VkGcaGUQ7CdXWEPwIgX7BotcptAz5BFcCOo9A4pTXZtM0Sm4UDnlNJjYZF2QFu+ey4g=
