os: linux
dist: jammy
language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/graalvm
branches:
  only:
  - main
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: dfcBsT4GsJ9wHV6XZzZ2fxKTYcgz6KOyUXLcVjn8asmVF0XdJwWjyZQVbvWh1ecz69t3RMk3mM1qNSJcObk9NkajVVtjedigwYDIZIRItn6jwm30RybZhfkskghSPbq8vn6pOnZ40j8ktHGGb/HnVqx9/zEnC5s16Dtfj9twIvjtlO/I9ZRK0z0OsQkBV5YynCKKjQvohtjt9unUD4oQJqrOdj4d6FkR+reDkGOp1pDwit2aLFWuWtwIWpSP4aNJkkJFAUJHqyUj4UZt0Bf24i8CgtZzLQB5SuLKowNLT6xhtd8i/MKHYoZ8QComYRPm8UD8gNb5J8dc1zSDyUNPp2bIaofgKvlLVqZiLtN9hArpxp73n0iecBrKszsKwEb4UQ9CAZBGeCDTGAYfA1SlExeEhi/YdGiKPbUR+VYTp4OUk6gbvuaJnlPmq0BZks1iHlsyOcs1GGefLuaYrgHlvfLyosx9xduBdyyeFt4dbirdLmGY+JgDdXflfntzQEVlOgrrsTQKlDSOVBtBzufOsef/WDS22JTKCGkB7Hq+NjTsv7KhTlILGe/2WGMvAwi+MfwqyF/0RfV8TuT45WN1Lhd9j9OsJGP4xuhpt2/QKUBkY0zrztOrU84flw/hFkKfprpWcyrw2W6ugqgam33HuUUQIourr8eVPltwSfnF3lA=

before_install:
  - ./install-graal.sh $HOME
  - export JAVA_HOME=$HOME/graalvm/graalvm
  - export PATH=JAVA_HOME/bin:$PATH
  - cp travis.settings.xml $HOME/.m2/settings.xml
install: true
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-utils
deploy:
- provider: script
  script: mvn clean deploy
  on:
    tags: true
env:
  global:
    secure: hXgBpskONS0Bwfp//8deUrpZQXlg1Pa+RqrVAOPhx9BPSabjKtFZ74d8f+QAmcwQJd5K8zILDd6upHTjhiyPAz2r4ZmnNOkI1hXNDL33wrZyVFh+bVP0jTQHltZ0I7byqut3OF9YDMlPCSDxxTBaY1asM6mBsROMQCSf17/3/XqadfzBC2KYS2c1sBFaSXyBsD9l1JeVV0Z8NSVTcOPGjTBOJe85T30FTJpZI1Zxlv8omfSTGjDVHRBHKq7SFdWCqC9HCWZDg3AQRq4lxfCc74iI9pNmx96GWq3c3RFHz/cjPPUGn/5nix9RYE7OQiiwToHG+dW8JrqLHvvX5xk5R0zh/C3mIXVZKXw9bISmdsO80QqQfxboCNEUaoFH51HscPqbrRWmtzgHNdQyUUAUpBVpG9yYZTJ0buRyNJFluaGad+itVWksWzNb/oAjNxMBzssuzXnAYFLQ3HdswRYX2fbHBxHhlFlBPtf6EGEK0vIJ8IEeq7eQbhJYQbnzjmA9jfxyNsU3hp/A8LicBmPNWGvvno3NGtWrHGu+VLU2TWqXYjWsE4Pso8fg0UKFbVrlVi+DCx5Okt5DHLNWBkFgObyg0Ec0ffOuJfaH/0i2VkGcaGUQ7CdXWEPwIgX7BotcptAz5BFcCOo9A4pTXZtM0Sm4UDnlNJjYZF2QFu+ey4g=
