os: linux
dist: focal
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: dfcBsT4GsJ9wHV6XZzZ2fxKTYcgz6KOyUXLcVjn8asmVF0XdJwWjyZQVbvWh1ecz69t3RMk3mM1qNSJcObk9NkajVVtjedigwYDIZIRItn6jwm30RybZhfkskghSPbq8vn6pOnZ40j8ktHGGb/HnVqx9/zEnC5s16Dtfj9twIvjtlO/I9ZRK0z0OsQkBV5YynCKKjQvohtjt9unUD4oQJqrOdj4d6FkR+reDkGOp1pDwit2aLFWuWtwIWpSP4aNJkkJFAUJHqyUj4UZt0Bf24i8CgtZzLQB5SuLKowNLT6xhtd8i/MKHYoZ8QComYRPm8UD8gNb5J8dc1zSDyUNPp2bIaofgKvlLVqZiLtN9hArpxp73n0iecBrKszsKwEb4UQ9CAZBGeCDTGAYfA1SlExeEhi/YdGiKPbUR+VYTp4OUk6gbvuaJnlPmq0BZks1iHlsyOcs1GGefLuaYrgHlvfLyosx9xduBdyyeFt4dbirdLmGY+JgDdXflfntzQEVlOgrrsTQKlDSOVBtBzufOsef/WDS22JTKCGkB7Hq+NjTsv7KhTlILGe/2WGMvAwi+MfwqyF/0RfV8TuT45WN1Lhd9j9OsJGP4xuhpt2/QKUBkY0zrztOrU84flw/hFkKfprpWcyrw2W6ugqgam33HuUUQIourr8eVPltwSfnF3lA=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-utils
deploy:
  provider: releases
  token:
    secure: fX5RXfrFOoglNSRhN6jLMd9D2p4kB/BMhQvmYFdWBFregJ6aL+elpqytGRdV84gi54vJo+BIkz4gNjQpuzKUbzdzOp2cdvQeANvK+WTCR2TGtwLb/yM+ozMTn4PAMsGJXTa9+kjYy/TAT3+zKS6Y2LYVPdd4SICdTX6nsLqdMotXndxHFvM2aXIao0rbjbCTQi/wZollYSzvgLFKAdxw3FtXgdez2UqZrV0a4KRXOGstzDwzB6f7DlNo58/PibLabzePIU59IVzZncSPThVPaNYidSBcU0fz1g2KJcDDvUvh/zanvucoFrrumcGxFQESLalOx6r3iVDQzpHnOU4kkZLvUwTHYLNsG3Ds3k+XHtj0iPAzCKEE+phERTLjBlNud/+gYpTX1M++S/ia+zz6C+QZsrcnEBQGc6kyKT04y0gFqujj9hpXhl4aMm/kQbOe/QnmhXcBV7hWxB+Mb3EEcuzux72GXTkL636CveWc0TFuSaMBFg0U1ypt8OPNVIj8Skc+C1lEJ4bVO224s8cp1MqR71TtMLGt/VADlwDXZAr9T5gu+9hRfknG9RiDtBCAytJ1F+TEQoQNWuxkzBshSb53jT2eFGX8oG4rKieIGC0pPx3eDizivGQ9+xGY8Nd2s2ApC6jwux/dj9valLA9Vz5IWAw+FALka2rVm8Cs5LA=
  file: target/vcf-utils.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
